version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
        environment:
          DATABASE_URL: "postgres://postgres@localhost:5432/build_db"
      - image: postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: build_db
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: pip3 install -r requirements.txt --user
      - run: python3 manage.py test --debug-mode
  deploy-prod:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: heroku maintenance on
          command: heroku maintenance:on --app ${HEROKU_APP_NAME_PROD}
      - run:
          name: heroku deploy
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PROD.git master
      - run:
          name: migrate db
          command: |
            heroku run python manage.py migrate --app ${HEROKU_APP_NAME_PROD}
      - run:
          name: heroku maintenance off
          command: heroku maintenance:off --app ${HEROKU_APP_NAME_PROD}
  deploy-stg:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: heroku deploy
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STG.git develop:master --force
      - run:
          name: migrate db
          command: |
            heroku run python manage.py migrate --app ${HEROKU_APP_NAME_STG}
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy-stg:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
